version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      TZ: 'Asia/Shanghai'
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
  oap:
    image: skywalking/oap:6.0.0-GA
    container_name: oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    volumes:
      - ./config:/skywalking/config:ro
    environment:
      TZ: 'Asia/Shanghai'
  ui:
    image: skywalking/ui:6.0.0-GA
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 2233:8080
    environment:
      collector.ribbon.listOfServers: oap:12800
      collector.ribbon.ReadTimeout: 20000
      TZ: 'Asia/Shanghai'