dubbo:
  scan:
    base-packages: com.example.dubbo.user
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: app-live
  consumer:
    check: false

spring:
  application:
    name: app-user
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 115.220.10.37:8848
